SELECT INTO OUTFILE '/path/to/file.csv' FIELDS TERMINATED BY OPTIONALLY ENCLOSED BY LINES TERMINATED BY '\n' FROM table_name; --Exporting Data to CSV
LOAD DATA INFILE '/path/to/file.csv' INTO TABLE table_name FIELDS TERMINATED BY ENCLOSED BY LINES TERMINATED BY '\n'; --Importing Data from CSV
